### ISSUE TITLE
Ignore error option

### ISSUE THREAD

**Issue by mlegenhausen** [csantanapr/grunt-cordovacli#13]
For some tasks like the `platform add` operation it would be nice to get a success even cordova returns an error. This would allow to make tasks that can optionally add the platform if it does not exists.

**Comment by csantanapr** [comment]
@mlegenhausen Any error from cordova returns status code 1, this means using the status code from cordova is useless, either is 0 or 1 for any error.
I added the feature using other methods in 0.6.0 hope it is useful

**Comment by mlegenhausen** [comment]
Thanks will take a look :)
