### ISSUE TITLE
Returns "undefined" when add plugins with --variable parameters

### ISSUE THREAD

**Issue by jonchenn** [csantanapr/grunt-cordovacli#23]
I was trying to add plugins using grunt-cordovacli with the following task:

      add_plugins: {
        options: {
          command: 'plugin',
          action: 'add',
          plugins: [
            'com.phonegap.plugins.facebookconnect --variable APP_ID=\"'+facebookAppId+'\" --variable APP_NAME=\"'+appName+'\"'
          ]
        }        
      }

and it just returns:

Running: ...somepath.../cordova plugin add "com.phonegap.plugins.facebookconnect" --variable APP_ID="xxxxxxx" --variable APP_NAME="xxxxxx"
undefined
Error
Error-> with Series tasksError

**Comment by danlbob** [comment]
Having this issue as well. Any workarounds?

**Comment by csantanapr** [comment]
Use the args property to pass variables

```javascript
add_facebook_plugin: {
        options: {
            command: 'plugin',
            action: 'add',  
            plugins: [                 
                'com.phonegap.plugins.facebookconnect'
            ],
            args:['--variable','APP_ID=fb12132424','--variable','APP_NAME=myappname']
        }
    }
```
