### ISSUE TITLE
plugin add in cordova 5.0

### ISSUE THREAD

**Issue by kreck** [csantanapr/grunt-cordovacli#24]
The Cordova project switched to npm for distributing plugins/their repository. Could you adjust the grunt plugin to use the new npm based repo instead of plugins.cordova.io? Maybe as an option while "plugins.cordova.io" is still running, so it doesn't break other peoples current grunt scripts.

Also see:
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

Best

**Comment by japrescott** [comment]
+1
