### ISSUE TITLE
Cannot include cordova-plugin-media

### ISSUE THREAD

**Issue by OptimusKrish** [csantanapr/grunt-cordovacli#29]
When trying to include media plugin via npm (cordova plugin add cordova-plugin-media) using grunt build the following error is thrown and media plugin is not getting included for android platform.

Error message:
Plugin doesn't support this project's cordova-android version. cordova-android: 4.1.1, failed version requirement: >=5.0.0-dev Skipping 'cordova-plugin-media' for android

![media_plugin_issue](https://cloud.githubusercontent.com/assets/7058950/12643115/2975310c-c5e0-11e5-9c8c-b67a21abff17.png)

**Comment by csantanapr** [comment]
This is not a problem with the grunt plugin.
You are trying to add a plugin version that is new and it doesn't support your old version of cordova-android
You can fix by upgrading your cordova-android or specifying an older version of the plugin
