### ISSUE TITLE
Feature request: add_plugins with variable

### ISSUE THREAD

**Issue by perpective2410** [csantanapr/grunt-cordovacli#7]
Hello,

With cordovacli, it is possible to add plugins with variable like:

cordova plugins add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=hibe

It would be nice to be able to do the following:

```
  add_plugins: {
      options: {
          command: 'plugin',
          action: 'add',
          plugins: [
               'https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=tel',
          ]
      }
    }
```

At the moment it is failing with the following error:

Running:node C:\dev\apps\turkey\hibe-webapp\web-app\node_modules\cordova\bin\cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.gi
t --variable URL_SCHEME=hibe
Fetching plugin "https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=hibe" via git clone
Error: Command failed: Cloning into 'C:\Users\valdelif\AppData\Local\Temp\plugman\git\1409081179796'...
fatal: unable to access 'https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=tel/': The requested URL returned error: 400

```
at ChildProcess.exithandler (child_process.js:637:15)
at ChildProcess.EventEmitter.emit (events.js:98:17)
at maybeClose (child_process.js:735:16)
at Socket.<anonymous> (child_process.js:948:11)
at Socket.EventEmitter.emit (events.js:95:17)
at Pipe.close (net.js:466:12)
```

> > Error
> > Error-> with Series tasksError
> > Warning: Task "cordovacli:add_plugins" failed. Use --force to continue.

As a workaround I am using the 'args' options like this:

```
  add_plugins: {
      options: {
          command: 'plugin',
          action: 'add',
          plugins: [
               'https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git',
          ],
          args: '--variable URL_SCHEME=tel'
      }
  },
```

However, it will add all the plugins with the args which is not the expected behavior. Let me know the feasability

Many thanks

**Comment by dream** [comment]
It needs to be included in the options object:

```javascript
                options: {
                    command: 'plugin',
                    action: 'add',
                    plugins: ["https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git"],
                    args: ["--variable URL_SCHEME=abc123"]
                }
```

**Comment by dream** [comment]
This worked for me:

```javascript
options: {
    command: 'plugin',
    action: 'add',
    args: ["--variable", " URL_SCHEME=abc123],
    plugins: ["https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git"]
}
```

**Comment by AlexanderSchmidt** [comment]
"args" as Array works! Thanks for the hint! This will make my live much easier in future :+1:
